services:

  postgres:
    image: postgres:18
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: submissionDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin

  redis:
    image: redis:7
    ports:
      - "6380:6379"